const actionTypes = {
    CHANGE_LOADING: 'CHANGE_LOADING',
    START_GAME: "START_GAME",
    FETCH_QUESTIONS_SUCCESS: "FETCH_QUESTIONS_SUCCESS",
    INCREASE_INDEX: "INCREASE_INDEX",
    SELECTED_ANSWER: "SELECTED_ANSWER",
    FINISH_GAME: "FINISH_GAME",
    RESET_STATE: "RESET_STATE",
};
  

export default actionTypes;
